### ISSUE TITLE
TiddlerFilename should not be global

### ISSUE THREAD

**Issue by Arlen22** [fallwest/tiddly-node-saver#1]
I glanced through your code and noticed that you are setting a global variable with request specific data in line 17 of server.js. You should instead either set a property on the request object or use the built-in variable set method (if the express request object has one).

**Comment by fallwest** [comment]
Hi Arlen22,
Thanks for the feedback!
Up to the present has indeed been just to allow editing one wiki at a time. 

I going to take a look at injecting the save script and possibly sending some post headers with the file name.

Best regards,

James

**Comment by fallwest** [comment]
This issue is now changed in latest check-in. I have added support for editing multiple wikis. I now inject the saveFile script which sends the filename as part of the post request.
